# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keepkit < Formula
  desc "Lightweight TUI for tracking versions of your favorite tools"
  homepage "https://github.com/stanlyzoolo/keepkit"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stanlyzoolo/keepkit/releases/download/v0.2.0/keepkit_v0.2.0_macos_x86_64.tar.gz"
      sha256 "4dbc0969d3063a6eb4de9c467dd1169343441fac3806679543a3a03a9f01cbaa"

      define_method(:install) do
        bin.install "keepkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stanlyzoolo/keepkit/releases/download/v0.2.0/keepkit_v0.2.0_macos_arm64.tar.gz"
      sha256 "62a3986b46af8d0ca2047b9b1ad67aec5d07db3efaab5659f206c912ae1fdaca"

      define_method(:install) do
        bin.install "keepkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanlyzoolo/keepkit/releases/download/v0.2.0/keepkit_v0.2.0_linux_x86_64.tar.gz"
      sha256 "08f62bab74caf05625532d4e1e596f587c555d5351353dbca5e3edd66d83c557"
      define_method(:install) do
        bin.install "keepkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanlyzoolo/keepkit/releases/download/v0.2.0/keepkit_v0.2.0_linux_arm64.tar.gz"
      sha256 "1e238709c16de506de5960d04edaa67cc4c078f5b9295981aa728798ee979240"
      define_method(:install) do
        bin.install "keepkit"
      end
    end
  end

  test do
    system "#{bin}/keepkit", "--version"
  end
end
